# Generated by Django 4.1.1 on 2022-10-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocoin',
            options={'verbose_name': 'coin', 'verbose_name_plural': 'coins'},
        ),
    ]
