# Generated by Django 4.1.1 on 2022-10-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptoaddress',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AddField(
            model_name='cryptoaddress',
            name='private_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
